name: ci
on: pull_request
jobs:

  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.7'
      - name: extract pip cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('setup.py') }}
          restore-keys: ${{ runner.os }}-pip-
      - run: |
          pip install --user --upgrade pip wheel
          pip install -e .[torrent,lint]
      - run: make lint

  tests-unit:
    name: "tests / unit"
    strategy:
      matrix:
        os:
          - ubuntu-latest
            #- macos-latest
            #- windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.7'
      - name: set pip cache dir
        id: pip-cache
        run: echo "::set-output name=dir::$(pip cache dir)"
      - name: extract pip cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('setup.py') }}
          restore-keys: ${{ runner.os }}-pip-
      - run: |
          pip install --user --upgrade pip wheel
          pip install -e .[torrent,test]
      - env:
          HOME: /tmp
        run: make test-unit-coverage

#  tests-integration:
#    name: "tests / integration"
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        test:
#          - datanetwork
#          - blockchain
#          - other
#    steps:
#      - name: Configure sysctl limits
#        run: |
#                sudo swapoff -a
#                sudo sysctl -w vm.swappiness=1
#                sudo sysctl -w fs.file-max=262144
#                sudo sysctl -w vm.max_map_count=262144
#
#      - name: Runs Elasticsearch
#        uses: elastic/elastic-github-actions/elasticsearch@master
#        with:
#                stack-version: 7.6.0
#      - uses: actions/checkout@v2
#      - uses: actions/setup-python@v1
#        with:
#          python-version: '3.7'
#      - if: matrix.test == 'other'
#        run: |
#          sudo apt-get update
#          sudo apt-get install -y --no-install-recommends ffmpeg
#      - name: extract pip cache
#        uses: actions/cache@v2
#        with:
#          path: ./.tox
#          key: tox-integration-${{ matrix.test }}-${{ hashFiles('setup.py') }}
#          restore-keys: txo-integration-${{ matrix.test }}-
#      - run: pip install tox-travis
#      - run: tox -e ${{ matrix.test }}

  build:
    needs: ["lint", "tests-unit"] #, "tests-integration"]
    name: "build"
    strategy:
      matrix:
        os:
          - ubuntu-16.04
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.7'
      - name: set pip cache dir
        id: pip-cache
        run: echo "::set-output name=dir::$(pip cache dir)"
      - name: extract pip cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('setup.py') }}
          restore-keys: ${{ runner.os }}-pip-
      - name: Setup
        run: |
          pip install --user --upgrade pip wheel
          pip install pyinstaller
          # https://stackoverflow.com/a/61693590
          # https://github.com/pypa/setuptools/issues/1963
          pip install --upgrade 'setuptools<45.0.0'
      - if: startsWith(matrix.os, 'ubuntu')
        name: Build & Run (Linux)
        run: |
          pip install -e .[torrent]
          pyinstaller --onefile --name lbrynet lbry/extras/cli.py
          chmod +x dist/lbrynet
          dist/lbrynet --version
      - if: startsWith(matrix.os, 'macos')
        name: Build & Run (Mac)
        run: |
          pip install -e .
          pyinstaller --onefile --name lbrynet lbry/extras/cli.py
          chmod +x dist/lbrynet
          dist/lbrynet --version
      - if: startsWith(matrix.os, 'windows')
        name: Build & Run (Windows)
        run: |
          pip install pywin32
          pip install -e .
          pyinstaller --additional-hooks-dir=scripts/. --icon=icons/lbry256.ico --onefile --name lbrynet lbry/extras/cli.py
          dist/lbrynet.exe --version
      - uses: actions/upload-artifact@v2
        with:
          name: lbrynet-${{ matrix.os }}
          path: dist/

  release:
    needs: ["build"]
    name: "release"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/download-artifact@v2
      - run: |
          ls -R
          pip install githubrelease

  docker:
    needs: ["build"]
    name: "build (docker)"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: fetch lbrynet binary
        uses: actions/download-artifact@v2
        with:
          name: lbrynet-ubuntu-16.04
      - run: |
          chmod +x lbrynet
          mv lbrynet docker
      - name: build and push docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: lbry/lbrynet
          path: docker
          dockerfile: docker/Dockerfile.wallet_server
          tag_with_ref: true
          tag_with_sha: true
          add_git_labels: true
